import { type NextPage } from "next";
import Head from "next/head";

import { Header } from "../components/Header";
import { useSession } from "next-auth/react";
import { api } from "~/utils/api";

const Home: NextPage = (props) => {
  return (
    <>
      <Head>
        <title>Notetaker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Content />
      </main>
    </>
  );
};

export default Home;

const Content: React.FC = () => {
  const { data: sessionData } = useSession();

  // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
  const { data: topics, refetch: refetchTopics } = api.topic.getAll.useQuery(
    undefined,
    {
      enabled: sessionData?.user !== undefined,
      retry: 0,
    }
  );

  return <div>{JSON.stringify(topics)}</div>
};

